gui:
  showRandomTip: true
os:
  editPreset: 'nvim'
keybinding:
  universal:
    quit: <c-g>
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
